services:
############################## URBANBOT ################################

  urbanbot-backend:
    build:
        context: ./signalR-backend
    ports:
       - "5024:80"
       - "5025:443"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=5025
        - ASPNETCORE_Kestrel__Certificates__Default__Password=fucker
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/signalR-backend.pfx
    volumes:
      - .\https:/https:ro
    networks:
        - backend
    restart : always


  urbanbot-frontend:
    build:
        context: ./signalr-frontend
        args:
          - URL=https://urbanbot-backend/hub
    ports:
        - "5026:3000"    
    networks:
        - backend
    restart : always


################################## NETWORKS ##################################################
networks:
  backend: